version: '3'
services:
    backend:
        image: node:lts-alpine
        container_name: agile-board.backend
        working_dir: /app
        entrypoint: /app/entrypoint.sh
        ports:
            - 3001:3001
        volumes:
            - ./backend:/app
        env_file:
            - /services/agile-board.backend.env

    webapp:
        image: node:lts-alpine
        container_name: agile-board.webapp
        working_dir: /app
        entrypoint: /app/entrypoint.sh
        ports:
            - 3000:80
        volumes:
            - ./webapp:/app
        depends_on:
            - backend
        env_file:
            - /services/agile-board.webapp.env
